@startuml
actor User
participant "Controller" as C
participant "Service" as S
participant "Repository" as R

User -> C: Request data
activate C

alt Option A
    C -> S: Retrieve data A
    activate S
    S -> R: Query data A
    activate R
    R --> S: Return data A to service
    deactivate R
    S --> C: Return data A to controller
    deactivate S
else Option B
    C -> S: Retrieve data B
    activate S
    S -> R: Query data B
    activate R
    R --> S: Return data B to service
    deactivate R
    S --> C: Return data B to controller
    deactivate S
end

C --> User: Return data to user
deactivate C
@enduml