@startuml
title UML时序图示例

actor 用户
participant 系统
participant 订单
participant 支付
participant 订单管理

用户 -> 系统:提交订单请求
系统 -> 订单管理:创建订单
订单管理 -> 订单:创建订单信息
订单 -> 支付:请求支付
支付 -> 系统:处理订单支付
系统 -> 订单管理:更新订单状态
订单管理 -> 订单:更新订单状态信息
@enduml